name: Android Build

on:
  push:
    branches:
      - main  # Trigger when code is pushed to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger for pull requests targeting 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Android SDK
        run: |
          wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
          unzip commandlinetools-linux-7583922_latest.zip
          rm commandlinetools-linux-7583922_latest.zip
          mv cmdline-tools /opt/android-sdk/cmdline-tools
          yes | /opt/android-sdk/cmdline-tools/bin/sdkmanager --sdk_root=/opt/android-sdk "platform-tools" "platforms;android-30" "build-tools;30.0.3"

      - name: Build APK
        run: |
          ./gradlew clean
          ./gradlew assembleDebug  # Or use assembleRelease to build a release version
      
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk
